SELECT 
	pps.PART_NO AS PartNo,
	sit.NAME AS Supplier,
	ipt.PLANNER_BUYER
FROM IFS.PURCHASE_PART_SUPPLIER_TAB AS pps
INNER JOIN IFS.SUPPLIER_INFO_TAB AS sit
	ON sit.SUPPLIER_ID = pps.VENDOR_NO
INNER JOIN IFS.INVENTORY_PART_TAB AS ipt
	ON ipt.PART_NO = pps.PART_NO
WHERE ipt.PART_STATUS = 'A'
AND ipt.CONTRACT = '2051';