SELECT
    PART_NO AS PartNo,
    QTY_ONHAND - QTY_RESERVED AS AvailableQty
FROM IFS.INVENTORY_PART_IN_STOCK_TAB
WHERE CONTRACT = '2051'
AND WAREHOUSE <> 'QUALITY'
AND AVAILABILITY_CONTROL_ID IS NULL;