SELECT
	PART_NO AS ParentPartNo,
	ENG_CHG_LEVEL AS RoutingRevision,
	COMPONENT_PART AS ComponentPart,
	QTY_PER_ASSEMBLY AS QpA
FROM IFS.MANUF_STRUCTURE_TAB
WHERE CONTRACT = '2051'
AND EFF_PHASE_OUT_DATE IS NULL
AND PART_NO NOT LIKE 'PLAN%'
AND COMPONENT_PART NOT LIKE 'NS%'
ORDER BY PART_NO;