SELECT
	pol.ORDER_NO AS PONo,
	pol.PART_NO AS PartNo,
	sit.NAME AS Supplier,
	pol.BUY_QTY_DUE AS Qty,
	pol.ROWSTATE AS State,
	pol.PLANNED_RECEIPT_DATE AS ReceiptDate,
	pol.LINE_NO AS 'LineNo',
	pol.RELEASE_NO AS 'ReleaseNo',
	pol.LINE_NO + ' - ' + pol.RELEASE_NO AS 'LineReleaseNo'
FROM IFS.PURCHASE_ORDER_LINE_TAB AS pol
INNER JOIN IFS.PURCHASE_PART_SUPPLIER_TAB AS pps
	ON pol.PART_NO = pps.PART_NO AND pol.PURCHASE_SITE = pps.CONTRACT
INNER JOIN IFS.SUPPLIER_INFO_TAB AS sit
	ON pol.INVOICING_SUPPLIER = sit.SUPPLIER_ID AND pol.INVOICING_SUPPLIER = pps.VENDOR_NO
WHERE pol.CONTRACT = '2051'
--AND pol.PART_NO = 'MMSU0120'
AND pol.ROWSTATE = 'Released'
ORDER BY pol.ORDER_NO, pol.LINE_NO, pol.RELEASE_NO;

