SELECT
	sor.PROPOSAL_NO AS 'Req Number',
	sor.PART_NO AS 'Part No',
	sor.ROWSTATE AS 'Status',
	CASE WHEN ipt.PLANNER_BUYER IN ('3001','3801') THEN 'BVI'
		ELSE 'Malosa'
		END AS 'Brand',
	sor.PROP_START_DATE AS 'Start Date',
	sor.PLAN_ORDER_REC AS 'Qty',
	CONCAT(YEAR(sor.PROP_START_DATE),'-',FORMAT(DATEPART(WEEK,sor.PROP_START_DATE),'00','en-US')) AS 'Week',
	ipp.MUL_ORDER_QTY AS 'Multiple Order Qty',
	CASE WHEN ipp.MUL_ORDER_QTY = 0
		THEN 0
		ELSE sor.PLAN_ORDER_REC/ipp.MUL_ORDER_QTY 
		END AS 'Boxes',
	CASE WHEN ipp.MUL_ORDER_QTY = 0
		THEN 0
		WHEN ipt.PLANNER_BUYER IN ('3001','3801') THEN (sor.PLAN_ORDER_REC/ipp.MUL_ORDER_QTY)/360
		WHEN ipt.PLANNER_BUYER IN ('5001') THEN (sor.PLAN_ORDER_REC/ipp.MUL_ORDER_QTY)/144
		ELSE 'Error'
		END AS 'Shipments'
FROM IFS.SHOP_ORDER_PROP_TAB AS sor
INNER JOIN IFS.INVENTORY_PART_TAB AS ipt
	ON sor.PART_NO = ipt.PART_NO AND sor.CONTRACT = ipt.CONTRACT
INNER JOIN IFS.INVENTORY_PART_PLANNING_TAB AS ipp
	ON sor.PART_NO = ipp.PART_NO AND sor.CONTRACT = ipp.CONTRACT
WHERE
	sor.CONTRACT = '2051'
	AND ipt.PLANNER_BUYER IN ('3001','3801','5001')
	AND sor.PROP_START_DATE > (GETDATE ()-365)
	AND sor.PROP_START_DATE < (GETDATE ()+365)
;
-- # Changelog

-- ## [1.0.0] - 2024-08-15

-- ### Added

-- - Initial Commit