SELECT
req.PROPOSAL_NO AS ProposalNo,
so.ORDER_NO AS SONo,
req.PART_NO AS PartNo,
ipt.PLANNER_BUYER AS Planner,
CASE WHEN ipt.PLANNER_BUYER = '5001' THEN 'Malosa'
ELSE 'BVI' END
	AS brand,
req.ROWSTATE AS Status,
req.CONTRACT AS Site,
pto.PLANNED_ORDER_REC AS PlanQty,
so.ORG_QTY_DUE AS SOQty,
req.PROP_START_DATE AS PlanStartDate,
so.ORG_START_DATE AS SOStartDate,
so.DATE_ENTERED AS CreateDate
FROM IFS.SHOP_ORDER_PROP_TAB AS req
LEFT OUTER JOIN IFS.PROPOSAL_TO_ORDER_TAB AS pto
    ON req.PROPOSAL_NO = pto.PROPOSAL_NO
LEFT OUTER JOIN IFS.SHOP_ORD_TAB AS so
    ON pto.SO_ORDER_NO = so.ORDER_NO
INNER JOIN IFS.INVENTORY_PART_TAB AS ipt
	ON req.PART_NO = ipt.PART_NO AND req.CONTRACT = ipt.CONTRACT
WHERE req.CONTRACT = '2051'
--AND req.PROP_START_DATE BETWEEN '01/01/2022' AND '12/31/2022'
AND ipt.PLANNER_BUYER IN ('3001','3801','5001')
;