SELECT
req.PROPOSAL_NO AS ProposalNo,
so.ORDER_NO AS SONo,
so.PART_NO AS PartNo,
ipt.PLANNER_BUYER AS Planner,
CASE WHEN ipt.PLANNER_BUYER = '5001' THEN 'Malosa'
ELSE 'BVI' END
	AS brand,
req.ROWSTATE AS Status,
so.ROWSTATE AS SOStatus,
so.CONTRACT AS Site,
pto.PLANNED_ORDER_REC AS PlanQty,
so.REVISED_QTY_DUE AS SOQty,
req.PROP_START_DATE AS PlanStartDate,
so.REVISED_START_DATE AS SOStartDate,
so.DATE_ENTERED AS CreateDate
FROM IFS.SHOP_ORD_TAB AS so
FULL JOIN IFS.PROPOSAL_TO_ORDER_TAB AS pto
    ON so.ORDER_NO = pto.SO_ORDER_NO
FULL JOIN IFS.SHOP_ORDER_PROP_TAB AS req
    ON req.PROPOSAL_NO = pto.PROPOSAL_NO
FULL JOIN IFS.INVENTORY_PART_TAB AS ipt
	ON so.PART_NO = ipt.PART_NO AND so.CONTRACT = ipt.CONTRACT
WHERE so.CONTRACT = '2051'
AND so.ROWSTATE = 'Released'
AND so.REVISED_START_DATE < (GETDATE ()+63)
AND ipt.PLANNER_BUYER IN ('3001','3801','5001')
--AND req.PROP_START_DATE BETWEEN '01/01/2022' AND '12/31/2022'
--AND so.ORDER_NO = '9517974'
;