SELECT
SOP.PROPOSAL_NO AS ProposalNo,
SO.ORDER_NO AS SONo,
SOP.PART_NO AS PartNo,
ipt.PLANNER_BUYER AS Planner,
CASE WHEN ipt.PLANNER_BUYER = '5001' THEN 'Malosa'
ELSE 'BVI' END
	AS brand,
SOP.ROWSTATE AS Status,
SOP.CONTRACT AS Site,
STO.PLANNED_ORDER_REC AS PlanQty,
SO.ORG_QTY_DUE AS SOQty,
SOP.PROP_START_DATE AS PlanStartDate,
SO.ORG_START_DATE AS SOStartDate,
SO.DATE_ENTERED AS CreateDate
FROM IFS.SHOP_ORDER_PROP_TAB SOP
LEFT OUTER JOIN IFS.PROPOSAL_TO_ORDER_TAB STO
    ON SOP.PROPOSAL_NO = STO.PROPOSAL_NO
LEFT OUTER JOIN IFS.SHOP_ORD_TAB SO
    ON STO.SO_ORDER_NO = SO.ORDER_NO
INNER JOIN IFS.INVENTORY_PART_TAB AS ipt
	ON SOP.PART_NO = ipt.PART_NO AND SOP.CONTRACT = ipt.CONTRACT
WHERE SOP.CONTRACT = '2051'
--AND SOP.PROP_START_DATE BETWEEN '01/01/2022' AND '12/31/2022'
AND ipt.PLANNER_BUYER IN ('3001','3801','5001')