SELECT
	--*,
	so.ORDER_NO AS 'SO No',
	so.PART_NO AS 'Part No',
	ipt.PLANNER_BUYER AS 'Planner',
	ipt.PRIME_COMMODITY AS 'Comm Group',
	so.ROWSTATE AS 'Status',
	so.REVISED_START_DATE AS 'Start Date',
	so.REVISED_QTY_DUE AS 'Rev Qty Due',
	CASE WHEN RIGHT(so.PART_NO,1) = 'S' THEN 'Sterile' ELSE 'Non-Sterile' END AS 'Sterility'
FROM IFS.SHOP_ORD_TAB AS so
INNER JOIN IFS.INVENTORY_PART_TAB AS ipt
	ON so.CONTRACT = ipt.CONTRACT AND so.PART_NO = ipt.PART_NO
WHERE so.CONTRACT = '2051'
AND so.ROWSTATE IN ('Planned')
AND ipt.PLANNER_BUYER IN ('3001','3801','5001','KIT SAMPLES','3802','3803','3804','3805')
ORDER BY so.REVISED_START_DATE
;