SELECT
	hrs.PART_NO,
	hrs.LABOR_CLASS_NO,
	CASE
		WHEN hrs.RUN_TIME_CODE IN (1,3) THEN hrs.LABOR_RUN_FACTOR
		WHEN hrs.RUN_TIME_CODE IN (2) THEN ISNULL(1/NULLIF(hrs.LABOR_RUN_FACTOR,0),0)
		ELSE 'Error' END AS 'Hours per Unit',
		'Kits' AS 'Area'
FROM IFS.ROUTING_OPERATION_TAB AS hrs
WHERE CONTRACT = '2051'
AND PHASE_OUT_DATE IS NULL
AND LABOR_CLASS_NO IN ('4936', '4948')

UNION

SELECT
	hrs.PART_NO,
	hrs.LABOR_CLASS_NO,
	CASE
		WHEN hrs.RUN_TIME_CODE IN (1,3) THEN hrs.LABOR_RUN_FACTOR
		WHEN hrs.RUN_TIME_CODE IN (2) THEN ISNULL(1/NULLIF(hrs.LABOR_RUN_FACTOR,0),0)
		ELSE 'Error' END AS 'Hours per Unit',
	CASE
		WHEN hrs.LABOR_CLASS_NO IN ('4931') THEN 'Manufacturing'
		WHEN hrs.LABOR_CLASS_NO IN ('4940') THEN 'Assembly'
		WHEN hrs.LABOR_CLASS_NO IN ('4941', '4947') THEN 'Packaging'
		WHEN hrs.LABOR_CLASS_NO IN ('4942') THEN 'Boxing'
		ELSE 'N/A' END AS 'Area'
FROM IFS.ROUTING_OPERATION_TAB AS hrs
WHERE CONTRACT = '2051'
AND PHASE_OUT_DATE IS NULL
AND LABOR_CLASS_NO IN ('4931', '4940', '4941', '4942', '4947');