SELECT
	ipt.PART_NO,
	ipt.LOCATION_NO,
	ipt.LOT_BATCH_NO,
	ipt.QTY_ONHAND - ipt.QTY_RESERVED AS 'Available Qty'
FROM IFS.INVENTORY_PART_IN_STOCK_TAB AS ipt
WHERE 
	ipt.CONTRACT = '2051'
	AND ipt.WAREHOUSE <> 'QUALITY'
	AND ipt.AVAILABILITY_CONTROL_ID IS NULL

UNION

SELECT
	ipt.PART_NO,
	ipt.LOCATION_NO,
	ipt.LOT_BATCH_NO,
	ipt.QTY_ONHAND - ipt.QTY_RESERVED AS 'Available Qty'
FROM IFS.INVENTORY_PART_IN_STOCK_TAB AS ipt
WHERE 
	ipt.CONTRACT = '2051'
	AND ipt.WAREHOUSE <> 'QUALITY'
	AND ipt.AVAILABILITY_CONTROL_ID IN ('GOODS-INWARDS')

;