SELECT
	ms.PART_NO AS 'Parent Part',
	ms.COMPONENT_PART AS 'Component Part',
	ms.QTY_PER_ASSEMBLY AS 'QpA',
	pt.PART_STATUS AS 'Parent Part Status',
	cpt.PART_STATUS AS 'Component Part Status'
FROM IFS.MANUF_STRUCTURE_TAB AS ms
LEFT JOIN IFS.INVENTORY_PART_TAB AS pt
	ON ms.PART_NO = pt.PART_NO AND ms.CONTRACT = pt.CONTRACT
LEFT JOIN IFS.INVENTORY_PART_TAB AS cpt
	ON ms.COMPONENT_PART = cpt.PART_NO AND ms.CONTRACT = cpt.CONTRACT
WHERE ms.CONTRACT = '2051'
	AND ms.EFF_PHASE_OUT_DATE IS NULL
;