DECLARE @POWeeksOut INT;

SET @POWeeksOut = 7;

SELECT
	pol.ORDER_NO AS 'PO Number',
	pol.PART_NO AS 'Part Number',
	pol.BUY_QTY_DUE * pol.CONV_FACTOR AS 'Qty Due',
	pol.INVOICING_SUPPLIER AS 'Supplier',
	pol.LINE_NO AS 'PO Line',
	pol.PROMISED_DELIVERY_DATE AS 'Promised Due Date'
FROM IFS.PURCHASE_ORDER_LINE_TAB AS pol
INNER JOIN IFS.PURCHASE_ORDER_TAB AS po
	ON pol.ORDER_NO = po.ORDER_NO
WHERE pol.PURCHASE_SITE = '2051'
	AND pol.ROWSTATE = 'Confirmed'
	AND pol.PROMISED_DELIVERY_DATE <= DATEADD(DAY, (@POWeeksOut+1)*7 - DATEPART(WEEKDAY, GETDATE()), GETDATE())
	AND pol.INVOICING_SUPPLIER NOT IN ('1060')
	--AND pol.ORDER_NO = 'DD143968582'
	--AND pol.PART_NO = '370520'
ORDER BY pol.PROMISED_DELIVERY_DATE
;
