SELECT
PART_NO,
LABOR_CLASS_NO,
RUN_TIME_CODE,
LABOR_RUN_FACTOR,
1/LABOR_RUN_FACTOR AS UNIT_HOURS
FROM IFS.ROUTING_OPERATION_TAB
WHERE CONTRACT = '2051'
AND PHASE_OUT_DATE IS NULL
AND LABOR_CLASS_NO IN ('4936', '4948');