SELECT req.PROPOSAL_NO AS Proposal,
req.PART_NO AS PartNo,
req.PROP_START_DATE AS ProposedStartDate,
req.REVISED_DUE_DATE AS RevisedDueDate,
req.PLAN_ORDER_REC AS Qty
FROM IFS.SHOP_ORDER_PROP_TAB AS req
INNER JOIN IFS.INVENTORY_PART_TAB AS ipt
	ON req.PART_NO = ipt.PART_NO AND req.CONTRACT = ipt.CONTRACT
WHERE req.CONTRACT = '2051'
AND req.ROWSTATE = 'ProposalCreated'
AND req.PROP_START_DATE < (GETDATE ()+63)
AND ipt.PLANNER_BUYER IN ('3001','3801','5001');