SELECT
so.ORDER_NO,
so.PART_NO,
so.REVISED_START_DATE,
so.REVISED_QTY_DUE
FROM IFS.SHOP_ORD_TAB AS so
INNER JOIN IFS.INVENTORY_PART_TAB AS ipt
	ON so.PART_NO = ipt.PART_NO AND so.CONTRACT = ipt.CONTRACT
WHERE so.CONTRACT = '2051'
AND so.ROWSTATE = 'Released'
AND so.REVISED_START_DATE < (GETDATE ()+63)
AND ipt.PLANNER_BUYER IN ('3001','3801','5001');