SELECT
	--*,
	req.PROPOSAL_NO AS 'Proposal/Order No',
	req.PART_NO AS 'Part No',
	CASE
		WHEN ipt.PLANNER_BUYER IN ('KIT SAMPLES') THEN 'Samples'
		WHEN ipt.PLANNER_BUYER IN ('3001','3801','5001') THEN 'Kits'
		ELSE 'I&K'
		END AS 'Area',
	CASE WHEN ipt.PLANNER_BUYER IN ('3001','3801') THEN 'KITEU'
		 WHEN ipt.PLANNER_BUYER IN ('5001') THEN 'MMK'
		 WHEN ipt.PLANNER_BUYER IN ('MBANNER','EGADOMSKA','KDUFFILL') THEN 'Purchased'
		 WHEN LEFT(req.PART_NO,4) = 'MMSU' THEN 'MMINS'
		 WHEN LEFT(req.PART_NO,4) = 'PLAN' THEN 'Plan'
		 WHEN LEFT(req.PART_NO,4) = 'MMSP' THEN 'Sample'
		 WHEN LEFT(req.PART_NO,1) = 'S' THEN 'Sample'
		 WHEN LEFT(req.PART_NO,1) = 'N' THEN 'Sample'
		 ELSE 'IK'
			END AS 'Further Area',
	ipt.PRIME_COMMODITY,
	req.PROP_START_DATE AS 'Start Date',
	CONCAT(YEAR(req.PROP_START_DATE),'-',FORMAT(DATEPART(WEEK,req.PROP_START_DATE),'00','en-US')) AS 'Week',
	req.PLAN_ORDER_REC AS 'Qty',
	CASE WHEN LEFT(req.PART_NO,4) = 'PLAN' THEN 'Plan Order' ELSE 'Normal Order' END AS 'Forecast Order'
	
FROM IFS.SHOP_ORDER_PROP_TAB AS req
INNER JOIN IFS.INVENTORY_PART_TAB AS ipt ON req.PART_NO = ipt.PART_NO AND req.CONTRACT = ipt.CONTRACT
--INNER JOIN IFS.ROUTING_OPERATION_TAB AS hrs ON req.PART_NO = hrs.PART_NO AND ipt.CONTRACT = hrs.CONTRACT

WHERE req.CONTRACT = '2051'
AND req.ROWSTATE = 'ProposalCreated'
--AND req.PART_NO IN ('590389')
AND req.PROP_START_DATE <= (GETDATE ()-14)

ORDER BY req.PROP_START_DATE
;