SELECT
so.ORDER_NO AS 'Shop Order Number'
,CASE WHEN so.PRIORITY_CATEGORY IS NULL THEN ''
	ELSE so.PRIORITY_CATEGORY
	END AS 'Priority Category'
,CASE
	WHEN ipt.PLANNER_BUYER IN ('KIT SAMPLES') THEN 'Samples'
	WHEN ipt.PLANNER_BUYER IN ('3001','3801','5001') THEN 'Kits'
	ELSE 'I&K'
	END AS 'Area'
,CASE WHEN ipt.PLANNER_BUYER IN ('3001','3801') THEN 'KITEU'
	 WHEN ipt.PLANNER_BUYER IN ('5001') THEN 'MMK'
	 WHEN ipt.PLANNER_BUYER IN ('MBANNER','EGADOMSKA','KDUFFILL') THEN 'Purchased'
	 WHEN LEFT(so.PART_NO,4) = 'MMSU' THEN 'MMINS'
	 WHEN LEFT(so.PART_NO,4) = 'PLAN' THEN 'Plan'
	 WHEN LEFT(so.PART_NO,4) = 'MMSP' THEN 'Sample'
	 WHEN LEFT(so.PART_NO,1) = 'S' THEN 'Sample'
	 WHEN LEFT(so.PART_NO,1) = 'N' THEN 'Sample'
	 ELSE 'IK'
		END AS 'Further Area'
,so.PART_NO AS 'Part Number'
,ipt.PLANNER_BUYER AS 'Planner'
,ipt.PRIME_COMMODITY AS 'Comm Group 1'
,so.ROWSTATE AS 'Status'
,so.EARLIEST_START_DATE AS 'E. Start Date'
,so.NEED_DATE AS 'Need Date'
,so.REVISED_START_DATE AS 'Start Date'
,CONCAT(YEAR(so.REVISED_START_DATE),'-',FORMAT(DATEPART(WEEK,so.REVISED_START_DATE),'00','en-US')) AS 'Week'
,so.REVISED_DUE_DATE AS 'End Date'
,so.REVISED_QTY_DUE AS 'Lot Size'
,so.QTY_COMPLETE AS 'Qty Complete'
,so.REVISED_QTY_DUE - so.QTY_COMPLETE - so.OPERATION_SCRAPPED AS 'Remaining Qty'
,so.ROUTING_REVISION AS 'Routing Rev.'
,pol.ORDER_NO AS 'Purchase Order Number'
,so.LAST_ACTIVITY_DATE AS 'Last Activity Date'

FROM IFS.SHOP_ORD_TAB AS so
INNER JOIN IFS.INVENTORY_PART_TAB AS ipt
	ON so.PART_NO = ipt.PART_NO AND so.CONTRACT = ipt.CONTRACT
LEFT JOIN IFS.PURCHASE_ORDER_LINE_TAB AS pol
	ON so.ORDER_NO = pol.DEMAND_ORDER_NO
WHERE so.CONTRACT = '2051'
AND so.ROWSTATE NOT IN ('Closed')
AND so.REVISED_START_DATE <= (GETDATE ()-14)
--AND so.LAST_ACTIVITY_DATE <= (GETDATE ()-14)
ORDER BY 
	--so.REVISED_START_DATE
	--so.LAST_ACTIVITY_DATE
	so.ORDER_NO
;